services:
  defame:
    image: tudamailab/defame
    build: .
    ports:
      - "3002"
    stdin_open: true
    tty: true
  firecrawl:
    image: tudamailab/firecrawl
    build: ./third_party/firecrawl
    ports:
      - "3002:3002"
