benchmark_kwargs:
  variant: dev
benchmark_name: averitec
fact_checker_kwargs:
  decompose: false
  decontextualize: false
  filter_check_worthy: false
  interpret: false
  max_iterations: 3
llm: llama3_70b
llm_kwargs:
  temperature: 0.01
mllm: null
mllm_kwargs: {}
n_samples: 100
random_sampling: false
sample_ids: null
tools_config:
  searcher:
    limit_per_search: 5
    search_engines:
    - averitec_kb
verbose: true
